#!/usr/bin/env bash
# Install nginx on your web-01
# Nginx should be listening on port 80
# Print 'Hello World!'

sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow  'Nginx HTTP'
sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html

#Test nginx configuration
sudo nginx -t
sudo service nginx reload