#!/usr/bin/env bash
# This script installs and configures Nginx to serve a 'Hello World!' page

#update package list
apt-get update -y

# Install nginx
apt-get install nginx -y

# Create a custom index.html with 'Hello World!'
echo "Hello World!" > /var/www/html/index.html

# Reload Nginx to apply changes
nginx -s reload

# Ensure port 80 is open (optional, based on your firewall configuration)
ufw allow 'Nginx HTTP'









