#!/usr/bin/env bash
# Script to configure Nginx with a custom 404 page

# Update the server and install Nginx
apt-get update -y
apt-get install -y nginx

# Start Nginx service
service nginx start

# Create the custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Modify the Nginx default server block configuration
sed -i "/server_name _;/ a\\
error_page 404 /custom_404.html;\\
location = /custom_404.html {\\
    internal;\\
}" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
